import { JiraTicket } from '@/types'

export const sampleTickets: JiraTicket[] = [
  // Authentication Epic
  {
    issueKey: 'GER-101',
    summary: 'Implement user authentication system',
    status: 'Done',
    assignee: 'Sarah Chen',
    priority: 'High',
    epic: 'Authentication',
    created: '2026-01-15',
    updated: '2026-03-10',
    dueDate: '2026-03-15',
    storyPoints: 8,
  },
  {
    issueKey: 'GER-102',
    summary: 'Add OAuth integration for Google',
    status: 'Done',
    assignee: 'Sarah Chen',
    priority: 'High',
    epic: 'Authentication',
    created: '2026-01-20',
    updated: '2026-03-12',
    dueDate: '2026-03-20',
    storyPoints: 5,
  },
  {
    issueKey: 'GER-103',
    summary: 'Create password reset flow',
    status: 'In Progress',
    assignee: 'Sarah Chen',
    priority: 'Medium',
    epic: 'Authentication',
    created: '2026-02-01',
    updated: '2026-03-16',
    dueDate: '2026-03-25',
    storyPoints: 3,
  },
  {
    issueKey: 'GER-104',
    summary: 'Add two-factor authentication',
    status: 'To Do',
    assignee: 'Sarah Chen',
    priority: 'Medium',
    epic: 'Authentication',
    created: '2026-02-10',
    updated: '2026-02-10',
    dueDate: '2026-04-01',
    storyPoints: 5,
  },

  // Dashboard Epic
  {
    issueKey: 'GER-201',
    summary: 'Design executive dashboard wireframes',
    status: 'Done',
    assignee: 'Marcus Rodriguez',
    priority: 'High',
    epic: 'Dashboard',
    created: '2026-01-10',
    updated: '2026-02-28',
    dueDate: '2026-03-01',
    storyPoints: 3,
  },
  {
    issueKey: 'GER-202',
    summary: 'Build KPI cards component',
    status: 'Done',
    assignee: 'Marcus Rodriguez',
    priority: 'High',
    epic: 'Dashboard',
    created: '2026-02-01',
    updated: '2026-03-05',
    dueDate: '2026-03-10',
    storyPoints: 5,
  },
  {
    issueKey: 'GER-203',
    summary: 'Implement charts with Recharts',
    status: 'Done',
    assignee: 'Emily Watson',
    priority: 'High',
    epic: 'Dashboard',
    created: '2026-02-05',
    updated: '2026-03-14',
    dueDate: '2026-03-15',
    storyPoints: 8,
  },
  {
    issueKey: 'GER-204',
    summary: 'Add real-time data updates',
    status: 'In Progress',
    assignee: 'Emily Watson',
    priority: 'Medium',
    epic: 'Dashboard',
    created: '2026-02-15',
    updated: '2026-03-17',
    dueDate: '2026-03-30',
    storyPoints: 5,
  },
  {
    issueKey: 'GER-205',
    summary: 'Create export to PDF functionality',
    status: 'To Do',
    assignee: 'Marcus Rodriguez',
    priority: 'Low',
    epic: 'Dashboard',
    created: '2026-02-20',
    updated: '2026-02-20',
    dueDate: '2026-04-15',
    storyPoints: 3,
  },

  // API Integration Epic
  {
    issueKey: 'GER-301',
    summary: 'Design REST API architecture',
    status: 'Done',
    assignee: 'James Kim',
    priority: 'High',
    epic: 'API Integration',
    created: '2026-01-05',
    updated: '2026-02-15',
    dueDate: '2026-02-20',
    storyPoints: 5,
  },
  {
    issueKey: 'GER-302',
    summary: 'Implement Jira API connector',
    status: 'Done',
    assignee: 'James Kim',
    priority: 'High',
    epic: 'API Integration',
    created: '2026-01-25',
    updated: '2026-03-08',
    dueDate: '2026-03-10',
    storyPoints: 8,
  },
  {
    issueKey: 'GER-303',
    summary: 'Add error handling and retry logic',
    status: 'Done',
    assignee: 'James Kim',
    priority: 'High',
    epic: 'API Integration',
    created: '2026-02-10',
    updated: '2026-03-11',
    dueDate: '2026-03-15',
    storyPoints: 5,
  },
  {
    issueKey: 'GER-304',
    summary: 'Implement rate limiting',
    status: 'In Progress',
    assignee: 'James Kim',
    priority: 'Medium',
    epic: 'API Integration',
    created: '2026-02-20',
    updated: '2026-03-15',
    dueDate: '2026-03-25',
    storyPoints: 3,
  },
  {
    issueKey: 'GER-305',
    summary: 'Add webhook support',
    status: 'Blocked',
    assignee: 'James Kim',
    priority: 'Medium',
    epic: 'API Integration',
    created: '2026-02-25',
    updated: '2026-03-10',
    dueDate: '2026-03-30',
    storyPoints: 5,
  },

  // Mobile App Epic
  {
    issueKey: 'GER-401',
    summary: 'Set up React Native project',
    status: 'Done',
    assignee: 'Priya Patel',
    priority: 'High',
    epic: 'Mobile App',
    created: '2026-01-08',
    updated: '2026-02-05',
    dueDate: '2026-02-10',
    storyPoints: 3,
  },
  {
    issueKey: 'GER-402',
    summary: 'Design mobile dashboard UI',
    status: 'Done',
    assignee: 'Priya Patel',
    priority: 'High',
    epic: 'Mobile App',
    created: '2026-01-15',
    updated: '2026-02-20',
    dueDate: '2026-02-25',
    storyPoints: 5,
  },
  {
    issueKey: 'GER-403',
    summary: 'Implement offline mode',
    status: 'In Progress',
    assignee: 'Priya Patel',
    priority: 'Medium',
    epic: 'Mobile App',
    created: '2026-02-01',
    updated: '2026-03-16',
    dueDate: '2026-03-20',
    storyPoints: 8,
  },
  {
    issueKey: 'GER-404',
    summary: 'Add push notifications',
    status: 'To Do',
    assignee: 'Priya Patel',
    priority: 'Medium',
    epic: 'Mobile App',
    created: '2026-02-10',
    updated: '2026-02-10',
    dueDate: '2026-04-01',
    storyPoints: 5,
  },
  {
    issueKey: 'GER-405',
    summary: 'Submit to App Store',
    status: 'Blocked',
    assignee: 'Priya Patel',
    priority: 'High',
    epic: 'Mobile App',
    created: '2026-02-15',
    updated: '2026-03-01',
    dueDate: '2026-04-15',
    storyPoints: 2,
  },

  // Testing Epic
  {
    issueKey: 'GER-501',
    summary: 'Set up automated testing framework',
    status: 'Done',
    assignee: 'Alex Thompson',
    priority: 'High',
    epic: 'Testing',
    created: '2026-01-12',
    updated: '2026-02-25',
    dueDate: '2026-03-01',
    storyPoints: 5,
  },
  {
    issueKey: 'GER-502',
    summary: 'Write unit tests for authentication',
    status: 'Done',
    assignee: 'Alex Thompson',
    priority: 'High',
    epic: 'Testing',
    created: '2026-02-05',
    updated: '2026-03-13',
    dueDate: '2026-03-15',
    storyPoints: 8,
  },
  {
    issueKey: 'GER-503',
    summary: 'Write integration tests for API',
    status: 'In Progress',
    assignee: 'Alex Thompson',
    priority: 'High',
    epic: 'Testing',
    created: '2026-02-15',
    updated: '2026-03-17',
    dueDate: '2026-03-25',
    storyPoints: 8,
  },
  {
    issueKey: 'GER-504',
    summary: 'Perform security audit',
    status: 'To Do',
    assignee: 'Alex Thompson',
    priority: 'High',
    epic: 'Testing',
    created: '2026-02-20',
    updated: '2026-02-20',
    dueDate: '2026-04-01',
    storyPoints: 5,
  },

  // Documentation Epic
  {
    issueKey: 'GER-601',
    summary: 'Write API documentation',
    status: 'Done',
    assignee: 'Lisa Anderson',
    priority: 'Medium',
    epic: 'Documentation',
    created: '2026-01-18',
    updated: '2026-03-09',
    dueDate: '2026-03-10',
    storyPoints: 3,
  },
  {
    issueKey: 'GER-602',
    summary: 'Create user guide',
    status: 'Done',
    assignee: 'Lisa Anderson',
    priority: 'Medium',
    epic: 'Documentation',
    created: '2026-02-01',
    updated: '2026-03-14',
    dueDate: '2026-03-15',
    storyPoints: 5,
  },
  {
    issueKey: 'GER-603',
    summary: 'Record demo videos',
    status: 'In Progress',
    assignee: 'Lisa Anderson',
    priority: 'Low',
    epic: 'Documentation',
    created: '2026-02-10',
    updated: '2026-03-16',
    dueDate: '2026-03-30',
    storyPoints: 3,
  },
  {
    issueKey: 'GER-604',
    summary: 'Update README and contribution guide',
    status: 'To Do',
    assignee: 'Lisa Anderson',
    priority: 'Low',
    epic: 'Documentation',
    created: '2026-02-20',
    updated: '2026-02-20',
    dueDate: '2026-04-10',
    storyPoints: 2,
  },
]
